### PR TITLE
I have made a card class and have implemented drawing from the deck

### PR DESCRIPTION
**Pull request by Codysseus**
This is a good base class. The default state of the deck is unshuffled. The faces of the cards are 1-13, and the suits are H, D, S, C.

### CODE REVIEW

**Comment by anisimon** [comment]
Sounds good. We should be able to get everything else running soon.

**Comment by Codysseus** [comment]
Seeing as you have oked this commit, I am going to merge it.

**Comment by Codysseus** [comment]
Before you merge it I do need to make some quick changes. I will post again when changes are made.

**Comment by anisimon** [comment]
public class Deck {
}
This is the only thing that I found in the program deck,java on Github, was there something else you created?

**Comment by anisimon** [comment]
```
public void shuffle() {
    for ( int i = deck.length-1; i > 0; i-- ) {
        int rand = (int)(Math.random()*(i+1));
        Card temp = deck[i];
        deck[i] = deck[rand];
        deck[rand] = temp;
    }
    cardsUsed = 0;
}
```

This is what I was thinking for the shuffle function..

**Comment by anisimon** [comment]
```
public Card dealCard() {
    if (cardsUsed == deck.length)
        throw new IllegalStateException("No cards are left in the deck.");
    cardsUsed++;
    return deck[cardsUsed - 1];
    //Cards are not literally removed from the array
    // that represents the deck.  Just keep track of how many cards
    // have been used.
}
```

This could help with the deal function.

**Comment by anisimon** [comment]
public class Deck {

```
private Card[] deck;
 // tracks the number of cards that have been dealt so far.
private int cardsUsed;
public Deck() {
    this(false);  // Just call the other constructor in this class.

}

public Deck( ) {

    deck = new Card[52];
    int cardCt = 0; // How many cards have been created so far.
    for ( int suit = 0; suit <= 3; suit++ ) {
        for ( int value = 1; value <= 13; value++ ) {
            deck[cardCt] = new Card(value,suit);
            cardCt++;
        }
    }

    cardsUsed = 0;
}
```

}
Here's something that could be used to create the deck. The function would be inside the Deck class. Let me know what you guys think. I just thought it would be good to compare it against what we already have.

**Pull request merged**
