### PR TITLE
Updating background

### PR DESCRIPTION
**Pull request by anisimon**
Adding background to our game.

### CODE REVIEW

**Comment by Codysseus** [comment]
This isn't a full feature, but I will accept it so that we can all see the cool background. For your next pull request, this should be a full feature.

**Comment by anisimon** [comment]
Alright, I will work on that.

**Comment by paublo96** [comment]
If you still need to know, I tested the background and it works. The picture does repeat though on the side of the screen.

**Comment by anisimon** [comment]
That's fine, I didn't want it to stretch out.

**Comment by ghost** [comment]
I like it, although we should change the font color to something lighter if we use this picture. the black text is very hard to see otherwise

**Pull request merged**
