### PR TITLE
Added a test for shuffle

### PR DESCRIPTION
**Pull request by anisimon**
I tested to see if the shuffled cards were equal to null or not.

### CODE REVIEW

**Comment by Codysseus** [comment]
Looks good to me! I hope the idea files don't break anything!

**Comment by anisimon** [comment]
Alright, thanks.

**Comment by paublo96** [comment]
It seems like next time we should not include the .idea files because I think they are different for everybody.

**Comment by ghost** [comment]
http://web.engr.oregonstate.edu/~hiltonm/classes/cs361/assignment1.html

**Pull request merged**
