### PR TITLE
Added functional New Game button

### PR DESCRIPTION
**Pull request by paublo96**
Button layout isn't correct yet, but I need to wait until other features are implemented.

### CODE REVIEW

**Comment by anisimon** [comment]
Would it be better to wait to merge then until everything else is there? Or did you want to take a risk and see what happens now?

**Comment by anisimon** [comment]
Wouldn't it be better to wait until that part it down and then merge? Or did you want to just risk it for now?

**Comment by paublo96** [comment]
Well I tested it and I'm sure the button works. I was just thinking we would put all the parts in there, then we can rearrange them later, but I can wait too,

**Comment by Codysseus** [comment]
The professor talked in class about waiting until a full feature is done, then submitting a pull request rather than submitting a bunch of them. I did this last time, and it wasn't good style.

**Pull request merged**
